# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
       containerRegistry: 'dockerhub'
       repository: 'mouchel/devops'
       command: 'buildAndPush'
       Dockerfile: '**/Dockerfile'
          
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'Terraformsrvconnection'
        backendAzureRmResourceGroupName: 'cmdockerlab'
        backendAzureRmStorageAccountName: 'cmdevopsstrorage'
        backendAzureRmContainerName: 'cmdevopsblob'
        backendAzureRmKey: 'Cn3WGSZFEX4kuGFoxUG00adHGkHF7zpwKe0kOY0HCqzu6u6zFt5UzA9NWbl59p8B8vBzC3+clHH2+AStPl+9hg=='
        
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'apply'
        commandOptions: 'tfplan -auto-approve'
        environmentServiceNameAzureRM: 'Simplon ARA Lyon Admin Cloud P22(393e3de3-0900-4b72-8f1b-fb3b1d6b97f1)'